"""Stable platform, registry and gate constants."""

from __future__ import annotations

EXPERIMENT_NAME = "knowledge-hub-mlops-churn"
REGISTERED_MODEL_NAME = "knowledge-hub-churn"
CANDIDATE_ALIAS = "candidate"
CHAMPION_ALIAS = "champion"

DEFAULT_ROWS = 1200
DEFAULT_BASELINE_SEED = 20260805
DEFAULT_CURRENT_SEED = 20260806
DEFAULT_RETRAIN_SEED = 20260807

MIN_TEST_F1 = 0.55
MIN_TEST_RECALL = 0.55
MAX_CANARY_F1_REGRESSION = 0.03
MAX_CANARY_DISAGREEMENT = 0.35
CANARY_PERCENT = 10
DRIFT_PSI_THRESHOLD = 0.20

PROMOTION_SCHEMA_VERSION = 1
DRIFT_SCHEMA_VERSION = 1
CANARY_SCHEMA_VERSION = 1
RELEASE_SCHEMA_VERSION = 1
ROLLBACK_SCHEMA_VERSION = 1
