name: kh-s3-versioning-minio

services:
  minio:
    image: cleanstart/minio:0.20260330.001845
    container_name: kh-lab-minio
    user: "0:0"
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:9000:9000"
