name: kh-redis-cache-ttl

services:
  redis:
    image: redis:7.4.10-alpine3.21
    container_name: kh-lab-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 20
